spring.application.name=ezploy

# The optional: prefix ensures your application still boots up in environments like Docker or Kubernetes where the
# physical file might not exist
spring.config.import=optional:file:.env[.properties]
# ===================================================================
# Database Connection (PostgreSQL)
# ===================================================================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# JPA / Hibernate Configurations
# ===================================================================
# Automatically creates, updates, or validates the database schema
spring.jpa.hibernate.ddl-auto=update

# Explicitly sets the SQL dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Prints SQL queries to the console for debugging
spring.jpa.show-sql=true

# Pretty-prints the console SQL output
spring.jpa.properties.hibernate.format_sql=true
